name: Metrics
on:
  workflow_dispatch:
  schedule:
    # Runs once a day at 05:00 UTC
    - cron: "0 5 * * *"

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
